Anisble Configurtaion
# config file for ansible in anisble directory on drive
# ===============================================

# This plug-ins into the yaml code and I get the gist

Genral

# this allow ssh get plugin the web
# ssh catman@20.120.0.25
# I was able to install elk into containers
#Then I was able to do sudo docker container list -a 
#check and locate contianer 
# Locate the etc file and yaml files there 
#nano [intsert file yaml]
# the coding was not a problem,but it was really really hard to do filebeat
#can i have more help with Kabana
#Was there a better solution than jumpbox
