# This is the default ansible 'hosts' file.
#
# It should live in /etc/ansible/hosts
I have [webservers] and [elkservers] group.

# Listed the IP Addresses of your webservers

[webservers]
10.0.0.5 ansible_python_interpreter=/usr/bin/python3
10.2.0.4 ansible_python_interpreter=/usr/bin/python3
10.2.0.5 ansible_python_interpreter=/usr/bin/python3

#  ELK server
# One IP address
[elkservers]
10.1.0.4 ansible_python_interpreter=/usr/bin/python3
