Metricbeat Configuration Example 
# This was hard I really di sleep over this.Can we please over this topic more

General 
# I really struggled on getting this ,but I wasnt able to make 
# nano Into yaml file
 
Dashboards 
#You can acces this file on elasticheart,but i couldn't get it to work
#https://cloud.elastic.co

Kibana 
#I hard time connecting this with my IP 
# It couldn't acces thsi file and I felt defeated after changing the ports
#http://[52.225.74.201]:5601/app/kibana
# I got it to work after messing around in my azure security inbound rules

Elastic Cloud 
#This is how you set up kibana 
#This is how you set up kibana metricbeat and filebeat work through this
#I really tried to set this up,but ufornately i couldn't connect my server even with yaml code
#https://cloud.elastic.co
