---
- name: download .deb from arrtifacts.elastic.co
  hosts: webservers
  become:true
  tasks:

  - name: download metricbeat .deb file
    apt:
     deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb


  - name: install metricbeat .deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb


  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansibe/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
      

   - name: enable docker service
     systemd: 
        name: docker
        enabled: yes
        

  - name: setup metricbeat
    command: metricbeat setup

   
  - name: start metricbeat service
    command: service metricbeat start

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes